// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvPRhfutkMpWGU5gqD99vlkT7sDVQu_zc',
    appId: '1:197587930400:web:42564a5c5a103fa77a1b45',
    messagingSenderId: '197587930400',
    projectId: 'auth-316a0',
    authDomain: 'auth-316a0.firebaseapp.com',
    storageBucket: 'auth-316a0.firebasestorage.app',
    measurementId: 'G-TRD3E2MTLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdjuo8_BTFSQiAzwFVv-8prugSoXWtgk4',
    appId: '1:197587930400:android:ff1ecb3cb2c4c8167a1b45',
    messagingSenderId: '197587930400',
    projectId: 'auth-316a0',
    storageBucket: 'auth-316a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5vRbfRtpMKMgrQ9WhOcJsZT_NVGsKry8',
    appId: '1:197587930400:ios:18b26c1fcf1708cf7a1b45',
    messagingSenderId: '197587930400',
    projectId: 'auth-316a0',
    storageBucket: 'auth-316a0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5vRbfRtpMKMgrQ9WhOcJsZT_NVGsKry8',
    appId: '1:197587930400:ios:18b26c1fcf1708cf7a1b45',
    messagingSenderId: '197587930400',
    projectId: 'auth-316a0',
    storageBucket: 'auth-316a0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvPRhfutkMpWGU5gqD99vlkT7sDVQu_zc',
    appId: '1:197587930400:web:e37cb205af00c4917a1b45',
    messagingSenderId: '197587930400',
    projectId: 'auth-316a0',
    authDomain: 'auth-316a0.firebaseapp.com',
    storageBucket: 'auth-316a0.firebasestorage.app',
    measurementId: 'G-MKQJ3CHWHB',
  );
}
